name: tests unitaires
on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:	
          python-version: ${{ matrix.python-version }}

      - name: Show branch / repo / OS
        run: |
          echo "Nom branche (ref): ${{ github.ref }}"
          echo "Nom branche (ref_name): ${{ github.ref_name }}"
          echo "Nom repo: ${{ github.repository }}"
          echo "OS runner: ${{ runner.os }}"

      - name: Show Python version
        run: python --version

      - name: Install pytest
        run: python -m pip install --upgrade pip pytest

      - name: Run tests
        run: python -m pytest bureltho/tp-504/TP1/test.py -v



